
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PrefabPath = _buf.ReadString();
    }

    public static Hero DeserializeHero(ByteBuf _buf)
    {
        return new Hero(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string PrefabPath;
   
    public const int __ID__ = 2245658;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefabPath:" + PrefabPath + ","
        + "}";
    }
}
}

