
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class LevelUp : Luban.BeanBase
{
    public LevelUp(ByteBuf _buf) 
    {
        Level = _buf.ReadInt();
        BaseHp = _buf.ReadFloat();
        BaseMp = _buf.ReadFloat();
        NeedXp = _buf.ReadFloat();
    }

    public static LevelUp DeserializeLevelUp(ByteBuf _buf)
    {
        return new LevelUp(_buf);
    }

    /// <summary>
    /// 等级
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 基础血量
    /// </summary>
    public readonly float BaseHp;
    /// <summary>
    /// 基础蓝量
    /// </summary>
    public readonly float BaseMp;
    /// <summary>
    /// 所需经验
    /// </summary>
    public readonly float NeedXp;
   
    public const int __ID__ = 1734438175;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "baseHp:" + BaseHp + ","
        + "baseMp:" + BaseMp + ","
        + "needXp:" + NeedXp + ","
        + "}";
    }
}
}

