
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public sealed partial class Monster : Luban.BeanBase
{
    public Monster(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        PrefabPath = _buf.ReadString();
    }

    public static Monster DeserializeMonster(ByteBuf _buf)
    {
        return new Monster(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 模型路径
    /// </summary>
    public readonly string PrefabPath;
   
    public const int __ID__ = -1393696838;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "prefabPath:" + PrefabPath + ","
        + "}";
    }
}
}

