
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Gas.TbGameEffect TbGameEffect {get; }
    public Gas.TbSkill TbSkill {get; }
    public Gas.TbSkillTransform TbSkillTransform {get; }
    public TbHero TbHero {get; }
    public TbLevelUp TbLevelUp {get; }
    public TbMonster TbMonster {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGameEffect = new Gas.TbGameEffect(loader("gas_tbgameeffect"));
        TbSkill = new Gas.TbSkill(loader("gas_tbskill"));
        TbSkillTransform = new Gas.TbSkillTransform(loader("gas_tbskilltransform"));
        TbHero = new TbHero(loader("tbhero"));
        TbLevelUp = new TbLevelUp(loader("tblevelup"));
        TbMonster = new TbMonster(loader("tbmonster"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameEffect.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbSkillTransform.ResolveRef(this);
        TbHero.ResolveRef(this);
        TbLevelUp.ResolveRef(this);
        TbMonster.ResolveRef(this);
    }
}

}
