
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace cfg
{
public partial class Tables
{
    public Gas.TbGameEffect TbGameEffect {get; }
    public Gas.TbSkill TbSkill {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbGameEffect = new Gas.TbGameEffect(loader("gas_tbgameeffect"));
        TbSkill = new Gas.TbSkill(loader("gas_tbskill"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbGameEffect.ResolveRef(this);
        TbSkill.ResolveRef(this);
    }
}

}
