
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg
{
public partial class TbLevelUp
{
    private readonly System.Collections.Generic.Dictionary<int, LevelUp> _dataMap;
    private readonly System.Collections.Generic.List<LevelUp> _dataList;
    
    public TbLevelUp(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, LevelUp>(n);
        _dataList = new System.Collections.Generic.List<LevelUp>(n);
        for(int i = n ; i > 0 ; --i)
        {
            LevelUp _v;
            _v = global::cfg.LevelUp.DeserializeLevelUp(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, LevelUp> DataMap => _dataMap;
    public System.Collections.Generic.List<LevelUp> DataList => _dataList;

    public LevelUp GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public LevelUp Get(int key) => _dataMap[key];
    public LevelUp this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

