
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class AttrBasedMagnitude : BaseMagnitude
{
    public AttrBasedMagnitude(ByteBuf _buf)  : base(_buf) 
    {
        Attr = _buf.ReadFloat();
        K = _buf.ReadFloat();
        B = _buf.ReadFloat();
    }

    public static AttrBasedMagnitude DeserializeAttrBasedMagnitude(ByteBuf _buf)
    {
        return new Gas.AttrBasedMagnitude(_buf);
    }

    public readonly float Attr;
    public readonly float K;
    public readonly float B;
   
    public const int __ID__ = 16082275;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "attr:" + Attr + ","
        + "k:" + K + ","
        + "b:" + B + ","
        + "}";
    }
}
}

