
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class AttrBasedMagnitude : BaseMagnitude
{
    public AttrBasedMagnitude(ByteBuf _buf)  : base(_buf) 
    {
        AttrBasedAttr = (Gas.EAttributeId)_buf.ReadInt();
        AttrBasedK = _buf.ReadFloat();
        AttrBasedB = _buf.ReadFloat();
    }

    public static AttrBasedMagnitude DeserializeAttrBasedMagnitude(ByteBuf _buf)
    {
        return new Gas.AttrBasedMagnitude(_buf);
    }

    public readonly Gas.EAttributeId AttrBasedAttr;
    public readonly float AttrBasedK;
    public readonly float AttrBasedB;
   
    public const int __ID__ = 16082275;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "attrBasedAttr:" + AttrBasedAttr + ","
        + "attrBasedK:" + AttrBasedK + ","
        + "attrBasedB:" + AttrBasedB + ","
        + "}";
    }
}
}

