
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public abstract partial class BaseMagnitude : Luban.BeanBase
{
    public BaseMagnitude(ByteBuf _buf) 
    {
    }

    public static BaseMagnitude DeserializeBaseMagnitude(ByteBuf _buf)
    {
        switch (_buf.ReadInt())
        {
            case Gas.SimpleFloatMagnitude.__ID__: return new Gas.SimpleFloatMagnitude(_buf);
            case Gas.AttrBasedMagnitude.__ID__: return new Gas.AttrBasedMagnitude(_buf);
            default: throw new SerializationException();
        }
    }

   

    public virtual void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "}";
    }
}
}

