
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum EAttributeId
    {
        None = 0,
        /// <summary>
        /// 基础生命
        /// </summary>
        HpBase = 1,
        /// <summary>
        /// 生命加成
        /// </summary>
        HpMult = 2,
        /// <summary>
        /// 额外生命
        /// </summary>
        HpAdd = 3,
    }

} 

