
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum EGameEffectStackType
    {
        /// <summary>
        /// 不堆叠
        /// </summary>
        None = 0,
        /// <summary>
        /// 来源堆叠
        /// </summary>
        Source = 1,
        /// <summary>
        /// 目标堆叠
        /// </summary>
        Target = 2,
    }

} 

