
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum EGameEffectDurationType
    {
        None = 0,
        /// <summary>
        /// 瞬间
        /// </summary>
        Instant = 1,
        /// <summary>
        /// 永久
        /// </summary>
        Infinite = 2,
        /// <summary>
        /// 持续
        /// </summary>
        Duration = 3,
    }

} 

