
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class FloatMagnitude : BaseMagnitude
{
    public FloatMagnitude(ByteBuf _buf)  : base(_buf) 
    {
        FloatB = _buf.ReadFloat();
    }

    public static FloatMagnitude DeserializeFloatMagnitude(ByteBuf _buf)
    {
        return new Gas.FloatMagnitude(_buf);
    }

    public readonly float FloatB;
   
    public const int __ID__ = 1642371849;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "floatB:" + FloatB + ","
        + "}";
    }
}
}

