
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class GameEffect : Luban.BeanBase
{
    public GameEffect(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Duration = global::cfg.Gas.GameEffectDuration.DeserializeGameEffectDuration(_buf);
        Tags = global::cfg.Gas.GameEffectTags.DeserializeGameEffectTags(_buf);
        Stack = global::cfg.Gas.GameEffectStack.DeserializeGameEffectStack(_buf);
        {int n0 = _buf.ReadSize(); Modifiers = new System.Collections.Generic.List<Gas.Modifiers>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { Gas.Modifiers _e0;  _e0 = global::cfg.Gas.Modifiers.DeserializeModifiers(_buf); Modifiers.Add(_e0);}}
    }

    public static GameEffect DeserializeGameEffect(ByteBuf _buf)
    {
        return new Gas.GameEffect(_buf);
    }

    public readonly int Id;
    public readonly Gas.GameEffectDuration Duration;
    public readonly Gas.GameEffectTags Tags;
    public readonly Gas.GameEffectStack Stack;
    public readonly System.Collections.Generic.List<Gas.Modifiers> Modifiers;
   
    public const int __ID__ = -1113892200;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Duration?.ResolveRef(tables);
        Tags?.ResolveRef(tables);
        Stack?.ResolveRef(tables);
        foreach (var _e in Modifiers) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "duration:" + Duration + ","
        + "tags:" + Tags + ","
        + "stack:" + Stack + ","
        + "modifiers:" + Luban.StringUtil.CollectionToString(Modifiers) + ","
        + "}";
    }
}
}

