
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class GameEffectDuration : Luban.BeanBase
{
    public GameEffectDuration(ByteBuf _buf) 
    {
        DurationType = (Gas.EGameEffectDurationType)_buf.ReadInt();
        Duration = _buf.ReadFloat();
        Period = _buf.ReadFloat();
        PeriodGe = _buf.ReadInt();
        PeriodGe_Ref = null;
    }

    public static GameEffectDuration DeserializeGameEffectDuration(ByteBuf _buf)
    {
        return new Gas.GameEffectDuration(_buf);
    }

    public readonly Gas.EGameEffectDurationType DurationType;
    public readonly float Duration;
    public readonly float Period;
    public readonly int PeriodGe;
    public Gas.GameEffect PeriodGe_Ref;
   
    public const int __ID__ = -1755188148;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        PeriodGe_Ref = tables.TbGameEffect.GetOrDefault(PeriodGe);
    }

    public override string ToString()
    {
        return "{ "
        + "durationType:" + DurationType + ","
        + "duration:" + Duration + ","
        + "period:" + Period + ","
        + "periodGe:" + PeriodGe + ","
        + "}";
    }
}
}

