
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class Modifier : Luban.BeanBase
{
    public Modifier(ByteBuf _buf) 
    {
        TargetAttr = (Gas.EAttributeId)_buf.ReadInt();
        Operate = (Gas.EModifierOperation)_buf.ReadInt();
        Magnitude = global::cfg.Gas.BaseMagnitude.DeserializeBaseMagnitude(_buf);
    }

    public static Modifier DeserializeModifier(ByteBuf _buf)
    {
        return new Gas.Modifier(_buf);
    }

    public readonly Gas.EAttributeId TargetAttr;
    public readonly Gas.EModifierOperation Operate;
    public readonly Gas.BaseMagnitude Magnitude;
   
    public const int __ID__ = -849296756;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Magnitude?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetAttr:" + TargetAttr + ","
        + "operate:" + Operate + ","
        + "magnitude:" + Magnitude + ","
        + "}";
    }
}
}

