
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class Modifiers : Luban.BeanBase
{
    public Modifiers(ByteBuf _buf) 
    {
        TargetAttr = (Gas.EAttributeId)_buf.ReadInt();
        Operate = (Gas.EModifierOperation)_buf.ReadInt();
        Magenitude = global::cfg.Gas.BaseMagnitude.DeserializeBaseMagnitude(_buf);
    }

    public static Modifiers DeserializeModifiers(ByteBuf _buf)
    {
        return new Gas.Modifiers(_buf);
    }

    public readonly Gas.EAttributeId TargetAttr;
    public readonly Gas.EModifierOperation Operate;
    public readonly Gas.BaseMagnitude Magenitude;
   
    public const int __ID__ = -558395545;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Magenitude?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "targetAttr:" + TargetAttr + ","
        + "operate:" + Operate + ","
        + "magenitude:" + Magenitude + ","
        + "}";
    }
}
}

