
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class SimpleFloatMagnitude : BaseMagnitude
{
    public SimpleFloatMagnitude(ByteBuf _buf)  : base(_buf) 
    {
        SimpleFloatK = _buf.ReadFloat();
        SimpleFloatB = _buf.ReadFloat();
    }

    public static SimpleFloatMagnitude DeserializeSimpleFloatMagnitude(ByteBuf _buf)
    {
        return new Gas.SimpleFloatMagnitude(_buf);
    }

    public readonly float SimpleFloatK;
    public readonly float SimpleFloatB;
   
    public const int __ID__ = -1815466597;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "simpleFloatK:" + SimpleFloatK + ","
        + "simpleFloatB:" + SimpleFloatB + ","
        + "}";
    }
}
}

