
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); TimelineAssets = new System.Collections.Generic.List<int>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { int _e0;  _e0 = _buf.ReadInt(); TimelineAssets.Add(_e0);}}
    }

    public static Skill DeserializeSkill(ByteBuf _buf)
    {
        return new Gas.Skill(_buf);
    }

    public readonly int Id;
    public readonly System.Collections.Generic.List<int> TimelineAssets;
   
    public const int __ID__ = -1845743940;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "timelineAssets:" + Luban.StringUtil.CollectionToString(TimelineAssets) + ","
        + "}";
    }
}
}

