
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class ConditionHasTag : BaseCondition
{
    public ConditionHasTag(ByteBuf _buf)  : base(_buf) 
    {
        {int n0 = _buf.ReadSize(); AllTag = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); AllTag.Add(_e0);}}
        {int n0 = _buf.ReadSize(); NoTag = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); NoTag.Add(_e0);}}
        {int n0 = _buf.ReadSize(); AnyTag = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); AnyTag.Add(_e0);}}
    }

    public static ConditionHasTag DeserializeConditionHasTag(ByteBuf _buf)
    {
        return new Gas.ConditionHasTag(_buf);
    }

    public readonly System.Collections.Generic.List<string> AllTag;
    public readonly System.Collections.Generic.List<string> NoTag;
    public readonly System.Collections.Generic.List<string> AnyTag;
   
    public const int __ID__ = 343173702;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "allTag:" + Luban.StringUtil.CollectionToString(AllTag) + ","
        + "noTag:" + Luban.StringUtil.CollectionToString(NoTag) + ","
        + "anyTag:" + Luban.StringUtil.CollectionToString(AnyTag) + ","
        + "}";
    }
}
}

