
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum EAttributeId
    {
        None = 0,
        /// <summary>
        /// 基础生命
        /// </summary>
        HpBase = 101,
        /// <summary>
        /// 生命加成
        /// </summary>
        HpMult = 102,
        /// <summary>
        /// 额外生命
        /// </summary>
        HpAdd = 103,
        /// <summary>
        /// 最大生命
        /// </summary>
        HpMax = 104,
        /// <summary>
        /// 当前生命
        /// </summary>
        HpNow = 105,
        /// <summary>
        /// 基础法力
        /// </summary>
        MpBase = 201,
        /// <summary>
        /// 法力加成
        /// </summary>
        MpMult = 202,
        /// <summary>
        /// 额外法力
        /// </summary>
        MpAdd = 203,
        /// <summary>
        /// 最大法力
        /// </summary>
        MpNow = 204,
        /// <summary>
        /// 当前法力
        /// </summary>
        MpMax = 205,
        /// <summary>
        /// 基础攻击
        /// </summary>
        AtkBase = 301,
        /// <summary>
        /// 攻击加成
        /// </summary>
        AtkMult = 302,
        /// <summary>
        /// 额外攻击
        /// </summary>
        AtkAdd = 303,
        /// <summary>
        /// 当前攻击
        /// </summary>
        AtkNow = 304,
        /// <summary>
        /// 基础火焰攻击
        /// </summary>
        FireAtkBase = 305,
        /// <summary>
        /// 火焰攻击加成
        /// </summary>
        FireAtkMult = 306,
        /// <summary>
        /// 额外火焰攻击
        /// </summary>
        FireAtkAdd = 307,
        /// <summary>
        /// 当前火焰攻击
        /// </summary>
        FireAtkNow = 308,
        /// <summary>
        /// 基础冰霜攻击
        /// </summary>
        IceAtkBase = 309,
        /// <summary>
        /// 冰霜攻击加成
        /// </summary>
        IceAtkMult = 310,
        /// <summary>
        /// 额外冰霜攻击
        /// </summary>
        IceAtkAdd = 311,
        /// <summary>
        /// 当前冰霜攻击
        /// </summary>
        IceAtkNow = 312,
        /// <summary>
        /// 基础闪电攻击
        /// </summary>
        LightAtkBase = 313,
        /// <summary>
        /// 闪电攻击加成
        /// </summary>
        LightAtkMult = 314,
        /// <summary>
        /// 额外闪电攻击
        /// </summary>
        LightAtkAdd = 315,
        /// <summary>
        /// 当前闪电攻击
        /// </summary>
        LightAtkNow = 316,
        /// <summary>
        /// 基础混乱攻击
        /// </summary>
        ChaosAtkBase = 317,
        /// <summary>
        /// 混乱攻击加成
        /// </summary>
        ChaosAtkMult = 318,
        /// <summary>
        /// 额外混乱攻击
        /// </summary>
        ChaosAtkAdd = 319,
        /// <summary>
        /// 当前混乱攻击
        /// </summary>
        ChaosAtkNow = 320,
        /// <summary>
        /// 基础护甲
        /// </summary>
        ArmorBase = 401,
        /// <summary>
        /// 护甲加成
        /// </summary>
        ArmorMult = 402,
        /// <summary>
        /// 额外护甲
        /// </summary>
        ArmorAdd = 403,
        /// <summary>
        /// 当前护甲
        /// </summary>
        ArmorNow = 404,
        /// <summary>
        /// 火焰抗性
        /// </summary>
        FireArmorNow = 501,
        /// <summary>
        /// 最大火焰抗性
        /// </summary>
        FireArmorMax = 502,
        /// <summary>
        /// 冰霜抗性
        /// </summary>
        IceArmorNow = 503,
        /// <summary>
        /// 最大冰霜抗性
        /// </summary>
        IceArmorMax = 504,
        /// <summary>
        /// 闪电抗性
        /// </summary>
        LightArmorNow = 505,
        /// <summary>
        /// 最大闪电抗性
        /// </summary>
        LightArmorMax = 506,
        /// <summary>
        /// 混乱抗性
        /// </summary>
        ChaosArmorNow = 507,
        /// <summary>
        /// 最大混乱抗性
        /// </summary>
        ChaosArmorMax = 508,
        /// <summary>
        /// 基础护盾
        /// </summary>
        ShieldBase = 601,
        /// <summary>
        /// 护盾加成
        /// </summary>
        ShieldMult = 602,
        /// <summary>
        /// 额外护盾
        /// </summary>
        ShieldAdd = 603,
        /// <summary>
        /// 最大护盾
        /// </summary>
        ShieldMax = 604,
        /// <summary>
        /// 当前护盾
        /// </summary>
        ShieldNow = 605,
    }

} 

