
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum EGameEffectStackExpireType
    {
        None = 0,
        /// <summary>
        /// 删除单层
        /// </summary>
        RemoveSingle = 1,
        /// <summary>
        /// 删除全部
        /// </summary>
        RemoveAll = 2,
    }

} 

