
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.Gas
{ 
    public enum ESkillStagePriority
    {
        /// <summary>
        /// 技能优先级
        /// </summary>
        None = 0,
        /// <summary>
        /// 普通
        /// </summary>
        Normal = 1,
        /// <summary>
        /// 优先
        /// </summary>
        High = 2,
        /// <summary>
        /// 强制
        /// </summary>
        Force = 3,
    }

} 

