
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class GameEffectStack : Luban.BeanBase
{
    public GameEffectStack(ByteBuf _buf) 
    {
        StackType = (Gas.EGameEffectStackType)_buf.ReadInt();
        CountLimit = _buf.ReadInt();
        RefreshDurationOnStack = _buf.ReadBool();
        RefreshPeriodOnStack = _buf.ReadBool();
        ExpireType = (Gas.EGameEffectStackExpireType)_buf.ReadInt();
    }

    public static GameEffectStack DeserializeGameEffectStack(ByteBuf _buf)
    {
        return new Gas.GameEffectStack(_buf);
    }

    public readonly Gas.EGameEffectStackType StackType;
    public readonly int CountLimit;
    public readonly bool RefreshDurationOnStack;
    public readonly bool RefreshPeriodOnStack;
    public readonly Gas.EGameEffectStackExpireType ExpireType;
   
    public const int __ID__ = 664098512;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "stackType:" + StackType + ","
        + "countLimit:" + CountLimit + ","
        + "refreshDurationOnStack:" + RefreshDurationOnStack + ","
        + "refreshPeriodOnStack:" + RefreshPeriodOnStack + ","
        + "expireType:" + ExpireType + ","
        + "}";
    }
}
}

