
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class GameEffectTags : Luban.BeanBase
{
    public GameEffectTags(ByteBuf _buf) 
    {
        {int n0 = _buf.ReadSize(); Assets = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Assets.Add(_e0);}}
        {int n0 = _buf.ReadSize(); Granted = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Granted.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ApplyRequired = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ApplyRequired.Add(_e0);}}
        {int n0 = _buf.ReadSize(); OnGoingRequired = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); OnGoingRequired.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ImmuneWhen = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ImmuneWhen.Add(_e0);}}
        {int n0 = _buf.ReadSize(); RemoveGeWith = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); RemoveGeWith.Add(_e0);}}
        {int n0 = _buf.ReadSize(); BlockGeWith = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); BlockGeWith.Add(_e0);}}
    }

    public static GameEffectTags DeserializeGameEffectTags(ByteBuf _buf)
    {
        return new Gas.GameEffectTags(_buf);
    }

    public readonly System.Collections.Generic.List<string> Assets;
    public readonly System.Collections.Generic.List<string> Granted;
    public readonly System.Collections.Generic.List<string> ApplyRequired;
    public readonly System.Collections.Generic.List<string> OnGoingRequired;
    public readonly System.Collections.Generic.List<string> ImmuneWhen;
    public readonly System.Collections.Generic.List<string> RemoveGeWith;
    public readonly System.Collections.Generic.List<string> BlockGeWith;
   
    public const int __ID__ = 1961096913;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "assets:" + Luban.StringUtil.CollectionToString(Assets) + ","
        + "granted:" + Luban.StringUtil.CollectionToString(Granted) + ","
        + "applyRequired:" + Luban.StringUtil.CollectionToString(ApplyRequired) + ","
        + "onGoingRequired:" + Luban.StringUtil.CollectionToString(OnGoingRequired) + ","
        + "immuneWhen:" + Luban.StringUtil.CollectionToString(ImmuneWhen) + ","
        + "removeGeWith:" + Luban.StringUtil.CollectionToString(RemoveGeWith) + ","
        + "blockGeWith:" + Luban.StringUtil.CollectionToString(BlockGeWith) + ","
        + "}";
    }
}
}

