
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class RelativeAttrMagnitude : BaseMagnitude
{
    public RelativeAttrMagnitude(ByteBuf _buf)  : base(_buf) 
    {
        RelativeAttrBase = (Gas.EAttributeId)_buf.ReadInt();
        RelativeAttrK = (Gas.EAttributeId)_buf.ReadInt();
        RelativeAttrB = (Gas.EAttributeId)_buf.ReadInt();
    }

    public static RelativeAttrMagnitude DeserializeRelativeAttrMagnitude(ByteBuf _buf)
    {
        return new Gas.RelativeAttrMagnitude(_buf);
    }

    public readonly Gas.EAttributeId RelativeAttrBase;
    public readonly Gas.EAttributeId RelativeAttrK;
    public readonly Gas.EAttributeId RelativeAttrB;
   
    public const int __ID__ = 907118110;
    public override int GetTypeId() => __ID__;

    public override void ResolveRef(Tables tables)
    {
        base.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "relativeAttrBase:" + RelativeAttrBase + ","
        + "relativeAttrK:" + RelativeAttrK + ","
        + "relativeAttrB:" + RelativeAttrB + ","
        + "}";
    }
}
}

