
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public sealed partial class SkillTransform : Luban.BeanBase
{
    public SkillTransform(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ToSkillId = _buf.ReadInt();
        Condition = global::cfg.Gas.BaseCondition.DeserializeBaseCondition(_buf);
    }

    public static SkillTransform DeserializeSkillTransform(ByteBuf _buf)
    {
        return new Gas.SkillTransform(_buf);
    }

    public readonly int Id;
    public readonly int ToSkillId;
    /// <summary>
    /// ConditionHasTag
    /// </summary>
    public readonly Gas.BaseCondition Condition;
   
    public const int __ID__ = 938946576;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        Condition?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "toSkillId:" + ToSkillId + ","
        + "condition:" + Condition + ","
        + "}";
    }
}
}

