
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public partial class TbGameEffect
{
    private readonly System.Collections.Generic.Dictionary<int, Gas.GameEffect> _dataMap;
    private readonly System.Collections.Generic.List<Gas.GameEffect> _dataList;
    
    public TbGameEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Gas.GameEffect>(n);
        _dataList = new System.Collections.Generic.List<Gas.GameEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Gas.GameEffect _v;
            _v = global::cfg.Gas.GameEffect.DeserializeGameEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Gas.GameEffect> DataMap => _dataMap;
    public System.Collections.Generic.List<Gas.GameEffect> DataList => _dataList;

    public Gas.GameEffect GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gas.GameEffect Get(int key) => _dataMap[key];
    public Gas.GameEffect this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

