
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace cfg.Gas
{
public partial class TbSkill
{
    private readonly System.Collections.Generic.Dictionary<int, Gas.Skill> _dataMap;
    private readonly System.Collections.Generic.List<Gas.Skill> _dataList;
    
    public TbSkill(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<int, Gas.Skill>(n);
        _dataList = new System.Collections.Generic.List<Gas.Skill>(n);
        for(int i = n ; i > 0 ; --i)
        {
            Gas.Skill _v;
            _v = global::cfg.Gas.Skill.DeserializeSkill(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Gas.Skill> DataMap => _dataMap;
    public System.Collections.Generic.List<Gas.Skill> DataList => _dataList;

    public Gas.Skill GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Gas.Skill Get(int key) => _dataMap[key];
    public Gas.Skill this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

